/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesAuditSecuriteApplicationRouteImport } from './routes/services/audit-securite-application'
import { Route as ServicesDeveloppementWebRouteImport } from './routes/services/developpement-web'
import { Route as ServicesIntegrationIaRouteImport } from './routes/services/integration-ia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAuditSecuriteApplicationRoute =
  ServicesAuditSecuriteApplicationRouteImport.update({
    id: '/services/audit-securite-application',
    path: '/services/audit-securite-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDeveloppementWebRoute =
  ServicesDeveloppementWebRouteImport.update({
    id: '/services/developpement-web',
    path: '/services/developpement-web',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIntegrationIaRoute = ServicesIntegrationIaRouteImport.update({
  id: '/services/integration-ia',
  path: '/services/integration-ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/contact': typeof ContactRoute
  '/projets': typeof ProjetsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/audit-securite-application': typeof ServicesAuditSecuriteApplicationRoute
  '/services/developpement-web': typeof ServicesDeveloppementWebRoute
  '/services/integration-ia': typeof ServicesIntegrationIaRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/contact': typeof ContactRoute
  '/projets': typeof ProjetsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/audit-securite-application': typeof ServicesAuditSecuriteApplicationRoute
  '/services/developpement-web': typeof ServicesDeveloppementWebRoute
  '/services/integration-ia': typeof ServicesIntegrationIaRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/contact': typeof ContactRoute
  '/projets': typeof ProjetsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/audit-securite-application': typeof ServicesAuditSecuriteApplicationRoute
  '/services/developpement-web': typeof ServicesDeveloppementWebRoute
  '/services/integration-ia': typeof ServicesIntegrationIaRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/contact'
    | '/projets'
    | '/blog/$slug'
    | '/services/audit-securite-application'
    | '/services/developpement-web'
    | '/services/integration-ia'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/contact'
    | '/projets'
    | '/blog/$slug'
    | '/services/audit-securite-application'
    | '/services/developpement-web'
    | '/services/integration-ia'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/contact'
    | '/projets'
    | '/blog/$slug'
    | '/services/audit-securite-application'
    | '/services/developpement-web'
    | '/services/integration-ia'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ContactRoute: typeof ContactRoute
  ProjetsRoute: typeof ProjetsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesAuditSecuriteApplicationRoute: typeof ServicesAuditSecuriteApplicationRoute
  ServicesDeveloppementWebRoute: typeof ServicesDeveloppementWebRoute
  ServicesIntegrationIaRoute: typeof ServicesIntegrationIaRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/audit-securite-application': {
      id: '/services/audit-securite-application'
      path: '/services/audit-securite-application'
      fullPath: '/services/audit-securite-application'
      preLoaderRoute: typeof ServicesAuditSecuriteApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/developpement-web': {
      id: '/services/developpement-web'
      path: '/services/developpement-web'
      fullPath: '/services/developpement-web'
      preLoaderRoute: typeof ServicesDeveloppementWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/integration-ia': {
      id: '/services/integration-ia'
      path: '/services/integration-ia'
      fullPath: '/services/integration-ia'
      preLoaderRoute: typeof ServicesIntegrationIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ContactRoute: ContactRoute,
  ProjetsRoute: ProjetsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesAuditSecuriteApplicationRoute: ServicesAuditSecuriteApplicationRoute,
  ServicesDeveloppementWebRoute: ServicesDeveloppementWebRoute,
  ServicesIntegrationIaRoute: ServicesIntegrationIaRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
